adminapp/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('admin_login',views.admin_login,name='admin_login'),
    path('admin_home',views.admin_home,name='admin_home'),
    path('admin_logout',views.admin_logout,name='admin_logout'),
    path('userslist',views.user_list,name='userslist'),

    path('edituser/<int:uid>/',views.edit_user,name='edituser'),
    path('deleteuser/<int:uid>/',views.delete_user,name='deleteuser'),
    path('adduser',views.add_user,name='adduser'),

    path('maincat_list',views.maincat_list,name='maincat_list'),
    path('editmaincatlist/<int:uid>/',views.edit_maincat_list,name='editmaincatlist'),
    path('deletemaincatlist/<int:uid>/',views.delete_maincat_list,name='deletemaincatlist'),
    path('addmaincatlist',views.add_maincat_list,name='addmaincatlist'),
    path('brandlist/<int:uid>/',views.brand_list,name='brandlist'),
    path('editsubcatlist/<int:uid>/',views.edit_subcat_list,name='editsubcatlist'),
    path('deletesubcatlist/<int:uid>/',views.delete_subcat_list,name='deletesubcatlist'),
    path('add_product/',views.add_product,name='add_product'),
    path('product_list/',views.product_list,name='product_list'),
    path('edit_product/<int:uid>/',views.edit_product,name='edit_product'),
    path('delete_product/<int:uid>/',views.delete_product,name='delete_product'),
    path('orders_list/',views.orders_list,name='orders_list'),
    path('edit_orderlist/<int:uid>/',views.edit_orderlist,name='edit_orderlist'),
    path('addorder/',views.add_order,name='add_order'),
    path('deleteorder/<int:uid>',views.delete_order,name='delete_order'),
    path('order_details/<int:uid>',views.order_details,name='order_details'),
    path('search_orderlist',views.search_orderlist,name='search_orderlist'),
    path('filter_orderlist/',views.filter_orderlist,name='filter_orderlist'),
    path('cancel_refund/<int:uid>',views.cancel_order_with_refund,name='cancel_refund'),


    path('couponlist/',views.coupon_list,name='couponlist'),
    path('addcoupon/',views.add_coupon,name='addcoupon'),
    path('editcoupon/<int:uid>',views.edit_coupon,name='editcoupon'),
    path('deletecoupon/<int:uid>',views.delete_coupon,name='deletecoupon'),
    path('userslist_coupon/',views.userslist_coupon,name='userslist_coupon'),
    path('my_couponlist/<int:uid>',views.my_couponlist,name='my_couponlist'),
    path('edit_mycoupon/<int:uid>',views.edit_mycoupon,name='edit_mycoupon'),
    path('add_mycoupon/',views.add_mycoupon,name='add_mycoupon'),
    path('delete_mycoupon/<int:uid>',views.delete_mycoupon,name='delete_mycoupon'),

    path('week_sales/',views.week_sales,name='week_sales'),
    path('current_year_sales/',views.current_year_sales,name='current_year_sales'),
    path('today_sales/',views.today_sales,name='today_sales')
    
    
]

electrokart/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('user_app.urls')),
    path('admin2/',include('adminapp.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

adminapp/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import timedelta
from django.utils import timezone 
# Create your models here.
class CustomerInfo(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    first_name=models.CharField(max_length=100, default=None, null=True)
    last_name=models.CharField(max_length=100, default=None, null=True)
    phone=models.BigIntegerField(default=None, null=True)
    user_email=models.EmailField(default=None, null=True)
    user_password=models.CharField(max_length=100, default=None, null=True)
    user_active=models.BooleanField(default=True)

class address(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    name=models.CharField(max_length=100)
    house_name=models.CharField(max_length=100)
    locality=models.CharField(max_length=100)
    city=models.CharField(max_length=100)
    zipcode=models.PositiveBigIntegerField()
    state=models.CharField(max_length=100)

    def __str__(self):
        return f'{self.name} - {self.city}'

class MainCategory(models.Model):
    name=models.CharField(max_length=100)

    def __str__(self):
        return self.name
    
class SubCategory(models.Model):
    main_category=models.ForeignKey(MainCategory,on_delete=models.CASCADE)
    name=models.CharField(max_length=100)

    def __str__(self):
        return self.name

class Product(models.Model):
    main_category=models.ForeignKey(MainCategory,on_delete=models.CASCADE) 
    title=models.CharField(max_length=100)
    our_price=models.FloatField()
    real_price=models.FloatField()
    description = models.TextField()
    main_img=models.ImageField(upload_to='main_imgs/')
    product_active=models.BooleanField(default=True)
    base_name=models.CharField(max_length=50,null=True,blank=True)
    variant_feature=models.CharField(max_length=50,null=True,blank=True)
    stock=models.PositiveBigIntegerField(default=10)
    def __str__(self):
        return self.title

    
class MultipleImages(models.Model):
    product=models.ForeignKey(Product,on_delete=models.CASCADE)
    images=models.ImageField(upload_to='main_imgs/')
    
    def __str__(self):
        return self.product.title
 
class ProductHighlights(models.Model):
    product=models.ForeignKey(Product,on_delete=models.CASCADE)
    highlight=models.CharField(max_length=200,null=True,blank=True)

    def __str__(self):
        return self.product.title

class AdditionalInfo(models.Model):
    product=models.ForeignKey(Product,on_delete=models.CASCADE)
    feature=models.CharField(max_length=50,null=True,blank=True)
    feature_description=models.CharField(max_length=200,null=True,blank=True)
    
    def __str__(self):
        return self.product.title

class Cart(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    product=models.ForeignKey(Product,on_delete=models.CASCADE)
    quantity=models.PositiveBigIntegerField(default=1)
    sub_total=models.PositiveBigIntegerField(default=0)
    is_paid=models.BooleanField(default=False)
    razor_pay_order_id=models.CharField(max_length=100, null=True, blank=True)
    razor_pay_payment_id=models.CharField(max_length=100,null=True, blank=True)
    razor_pay_payment_signature=models.CharField(max_length=100,null=True,blank=True)


    def __str__(self):
        return self.user.username
    @property
    def total_cost(self):
        return self.quantity * self.product.our_price
    def save(self, *args, **kwargs):
        self.sub_total = self.total_cost  # Calculate subtotal based on quantity and product price
        super(Cart, self).save(*args, **kwargs)
STATUS_CHOICE=(
    ('pending','pending'),
    ('Accepted','Accepted'),
    ('Packed','Packed'),
    ('On the way','On the way'),
    ('delivered','delivered'),
    ('Cancelled','Cancelled'),
    ('requested for cancellation','requested for cancellation'),
    ('requested for cancellation and refund','requested for cancellation and refund'),
    ('requested for return','requested for return'),
    ('returned','returned')
    
)

class Order(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    address=models.ForeignKey(address,on_delete=models.CASCADE)
    total_amount=models.PositiveBigIntegerField(default=0)
    discount_amount=models.PositiveBigIntegerField(default=0)
    status=models.CharField(max_length=50,choices=STATUS_CHOICE,default='pending')
    ordered_date=models.DateTimeField(auto_now_add=True)
    payment_mode=models.CharField(max_length=100,default='Cash on Delivery')
    
    def original_price(self):
        return self.total_amount + self.discount_amount


class OrderPlaced(models.Model):
    order=models.ForeignKey(Order,on_delete=models.CASCADE)
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    address=models.ForeignKey(address,on_delete=models.CASCADE)
    Product=models.ForeignKey(Product,on_delete=models.CASCADE)
    ordered_date=models.DateTimeField(auto_now_add=True)
    delivery_date = models.DateTimeField(null=True, blank=True)
    quantity = models.PositiveBigIntegerField(default=1)
    status=models.CharField(max_length=50,choices=STATUS_CHOICE,default='pending')
    discount_status=models.BooleanField(default=False)
    payment_status=models.CharField(max_length=100,default='Cash on Delivery')
    def save(self, *args, **kwargs):
        if not self.ordered_date:
            self.ordered_date = timezone.now()  # Assuming you're using Django's timezone
        if not self.delivery_date:
            self.delivery_date = self.ordered_date + timedelta(days=3)
        super().save(*args, **kwargs)
    @property
    def total_cost(self):
        return self.quantity * self.Product.our_price


class Coupon(models.Model):
    code = models.CharField(max_length=50, unique=True)
    discount = models.DecimalField(max_digits=10, decimal_places=2,default=0)
    valid_from = models.DateTimeField()
    valid_to = models.DateTimeField()
    active = models.BooleanField(default=True)

    def is_valid(self):
        return self.valid_from <= timezone.now() <= self.valid_to and self.active

    def __str__(self):
        return self.code


class UserCoupon(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    coupon=models.ForeignKey(Coupon,on_delete=models.CASCADE)
    is_used=models.BooleanField(default=True)

    def __str__(self):
        return f'{self.user} - {self.coupon}'

class wallet(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    balance_amount=models.PositiveBigIntegerField(default=0)

    def __str__(self):
        return self.user.username

templates/myadmin/add_coupon.html
{% extends 'myadmin/base.html' %}
{% block content %}
{% load static %}
        <section class="content-main">
            <div class="content-header">
                <div>
                    <h2 class="content-title card-title">Create coupons</h2>
                    <p>Create coupons here</p>
                </div>
                <div>
                    
                    <a href="{% url 'couponlist' %}" class="btn btn-primary btn-sm rounded">back</a>
                </div>
            </div>
            <div class="card mb-4">
                
                <div class="card-body">
                    <form method="POST">
                        {% csrf_token %}
                        <label>New coupon code</label><br>
                        <input type="text" name=code class="form-control" style="width:200px;">
                        <br><br>
                        <label>Discount Rate</label><br>
                        <input type="number" name="discount" min="1" max="100" step="1" class="form-control" style="width:200px;"><br><br>
                        <label>Valid from</label><br>
                        <input type="datetime-local" id="valid_from" name="valid_from" class="form-control" style="width:200px;"><br><br>
                        <label>Valid to</label><br>
                        <input type="datetime-local" id="valid_to" name="valid_to" class="form-control" style="width:200px;"><br><br>
                        <label>Is Active</label>
                    
                        <select name="status" id="status" class="form-control" style="width:200px;">
                            <option value="active">Active</option>
                            <option value="inactive">Inactive</option>
                        </select>
                        <br><br>
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </form>
                    
                </div>
            </div> <!-- card end// -->
            
        </section> <!-- content-main end// -->
{% endblock %}

templates/myadmin/add_maincat_list.html
{% extends 'myadmin/base.html' %}
{% block content %}
{% load static %}
        <section class="content-main">
            <div class="content-header">
                <div>
                    <h2 class="content-title card-title">Add user</h2>
                </div>
                <div>
                    <a href="{% url 'maincat_list' %}" class="btn btn-primary btn-sm rounded">back</a>
                </div>
            </div>
            <div class="card mb-4">
                 <!-- card-header end// -->
                <div class="card-body">
                    <form action="{% url 'addmaincatlist' %}" method="POST">{% csrf_token %}
                        {% if messages %}
                          {% for message in messages %}
                            <p class="message {% if message.tags %}{{ message.tags }}{% endif %}">{{ message }}</p>
                          {% endfor %}
                        {% endif %}
                        <div>
                          <label for="username">Enter new Category</label>
                          <input type="text" id="catname" name="catname" class="form-control" style="width:200px;" required><br><br>
                          
                          <button type="submit" class="btn btn-primary">Add Category</button>
                        </div>
                      </form>
                </div> <!-- card-body end// -->
            </div> <!-- card end// -->
            
        </section> <!-- content-main end// -->
{% endblock %}

templates/myadmin/adduser.html
{% extends 'myadmin/base.html' %}
{% block content %}
{% load static %}
        <section class="content-main">
            <div class="content-header">
                <div>
                    <h2 class="content-title card-title">Add user</h2>
                    
                </div>
                <div>
                    
                    <a href="{% url 'userslist' %}" class="btn btn-primary btn-sm rounded">back</a>
                </div>
            </div>
            <div class="card mb-4">
                 <!-- card-header end// -->
                <div class="card-body">
                  <form action="{% url 'adduser' %}" method="POST">{% csrf_token %}
                    {% if messages %}
                      {% for message in messages %}
                        <p class="message {% if message.tags %}{{ message.tags }}{% endif %}">{{ message }}</p>
                      {% endfor %}
                    {% endif %}
                    <div>
                      <label for="username">Username:</label>
                      <input type="text" id="username" name="username" class="form-control" style="width:200px;" required><br><br>
                      <label for="email">Email:</label>
                      <input type="email" id="email" name="email" class="form-control" style="width:200px;" required><br><br>
                      <label for="password">Password:</label>
                      <input type="password" id="password" name="pass1" class="form-control" style="width:200px;" required><br><br>
                      <button type="submit" class="btn btn-primary">Add User</button>
                    </div>
                  </form>
                </div> <!-- card-body end// -->
            </div> <!-- card end// -->
            
        </section> <!-- content-main end// -->
{% endblock %}

templates/myadmin/brand_list.html
{% extends 'myadmin/base.html' %}
{% block content %}
{% load static %}
<section class="content-main">
    <div class="content-header">
        <div>
            <h2 class="content-title card-title">{{main_category.name}}</h2>
            <p>These are the available brands of {{main_category.name}} .</p>
        </div>
        <div>
            
            <a href="{% url 'maincat_list' %}" class="btn btn-primary btn-sm rounded">back to Main</a>
        </div>
    </div>
    <div class="card mb-4">
        <header class="card-header">
            <div class="row align-items-center">
                <div class="col col-check flex-grow-0">
                    <div class="form-check ms-2">
                        <input class="form-check-input" type="checkbox" value="">
                    </div>
                </div>
                <div class="col-md-3 col-12 me-auto mb-md-0 mb-3">
                    
                </div>
                <div class="col-md-2 col-6">
                    
                </div>
                <div class="col-md-2 col-6">
                    
                </div>
            </div>
        </header> <!-- card-header end// -->
        <div class="card-body">
            <article class="itemlist">
                <div class="row align-items-center">
                    <div class="col col-check flex-grow-0">
                        <div >
                            ID
                        </div>
                    </div>
                    
                    <div class="col-lg-4 col-sm-4 col-8 flex-grow-1 col-name">
                        <a class="itemside" href="#"></a>
                            <div class="info">
                                <h6 class="mb-0">category name</h6>
                            </div>
                        </a>
                    </div>
                    
                    
                    
                    <div class="col-lg-2 col-sm-2 col-4 col-action text-end">
                        <span>Actions</span>
                    </div>
                </div> <!-- row .// -->
            </article> <!-- itemlist  .// -->
            {% for i in sub_category%}
            <article class="itemlist">
                <div class="row align-items-center">
                    <div class="col col-check flex-grow-0">
                        <div >
                            {{forloop.counter}}
                        </div>
                    </div>
                    
                    <div class="col-lg-4 col-sm-4 col-8 flex-grow-1 col-name">
                        <a class="itemside" href="#"></a>
                            <div class="info">
                                <h6 class="mb-0">{{i.name}}</h6>
                            </div>
                        </a>
                    </div>
                    
                    
                    
                    <div class="col-lg-2 col-sm-2 col-4 col-action text-end">
                        <a href="{% url 'editsubcatlist' uid=i.id %}">
                            <i class="material-icons md-edit"></i> Edit
                        </a>
                        <a href="{% url 'deletesubcatlist' uid=i.id %}" class="btn btn-sm font-sm btn-light rounded">
                            <i class="material-icons md-delete_forever"></i> Delete
                        </a>
                    </div>
                </div> <!-- row .// -->
            </article> <!-- itemlist  .// -->
            {% endfor %}
        </div> <!-- card-body end// -->
        
        
    </div> <!-- card end// -->
    <h3>Add brand</h3>
        <form action="{% url 'brandlist' uid=main_category.pk %}" method="POST">{% csrf_token %}
        {% if messages %}
            {% for message in messages %}
                <p class="message {% if message.tags %}{{ message.tags }}{% endif %}">{{ message }}</p>
            {% endfor %}
        {% endif %}
        <div>
            <label for="categoryname">Enter new brand</label>
            <input type="text" id="brandname" name="brandname" required>

            <button type="submit">Add</button>
        </div>


        </form>
    <div class="pagination-area mt-30 mb-50">
        <nav aria-label="Page navigation example">
            <ul class="pagination justify-content-start">
                <li class="page-item active"><a class="page-link" href="#">01</a></li>
                <li class="page-item"><a class="page-link" href="#">02</a></li>
                <li class="page-item"><a class="page-link" href="#">03</a></li>
                <li class="page-item"><a class="page-link dot" href="#">...</a></li>
                <li class="page-item"><a class="page-link" href="#">16</a></li>
                <li class="page-item"><a class="page-link" href="#"><i class="material-icons md-chevron_right"></i></a></li>
            </ul>
        </nav>
    </div>
</section> <!-- content-main end// -->
{% endblock %}

templates/myadmin/edit_coupon.html
{% extends 'myadmin/base.html' %}
{% block content %}
{% load static %}
        <section class="content-main">
            <div class="content-header">
                <div>
                    <h2 class="content-title card-title">Edit coupons</h2>
                    <p>Edit coupons here</p>
                </div>
                <div>
                    <a href="{% url 'couponlist' %}" class="btn btn-primary btn-sm rounded">Back</a>
                </div>
            </div>
            <div class="card mb-4">
                
                <div class="card-body">
                    <form method="POST">
                        {% csrf_token %}
                        <label>New coupon code</label><br>
                        <input type="text" class="form-control" style="width:200px;" value="{{my_coupon.code}}" name=code>
                        <br><br>
                        <label>Discount Rate* %</label><br>
                        <input type="number" class="form-control" style="width:200px;" value="{{my_coupon.discount}}" name="discount" min="1" max="100" step="1"><br><br>
                        <label>Valid from*</label><br>
                        <input type="datetime-local" class="form-control" style="width:200px;" value="{{my_coupon.valid_from|date:'Y-m-d\TH:i'}}" id="valid_from" name="valid_from"><br><br>
                        <label>Valid to*</label><br>
                        <input type="datetime-local" class="form-control" style="width:200px;" value="{{my_coupon.valid_to|date:'Y-m-d\TH:i'}}" id="valid_to" name="valid_to"><br><br>
                        <label>Is Active</label>
                    
                        <select name="status" class="form-control" style="width:200px;" id="status">
                            <option value="active">Active</option>
                            <option value="inactive">Inactive</option>
                        </select>
                        <br><br>
                        <button class="btn btn-primary" type="submit">Submit</button>
                    </form>
                    
                </div>
            </div> <!-- card end// -->
            
        </section> <!-- content-main end// -->
{% endblock %}

templates/myadmin/edit_mycoupon.html
{% extends 'myadmin/base.html' %}
{% block content %}
{% load static %}
        <section class="content-main">
            <div class="content-header">
                <div>
                    <h2 class="content-title card-title">Change status of your coupons</h2>
                    <p>electrokart.com</p>
                </div>
                <div>
                    
                    
                </div>
            </div>
            <div class="card mb-4">
                
                <div class="card-body">
                    <form method="POST">
                        {% csrf_token %}
                        <label>Is used or not</label><br>
                        <select name="status" id="status">
                            <option value="used">Used</option>
                            <option value="unused">Unused</option>
                        </select>
                        <br><br>
                        <button type="submit">Submit</button>
                    </form>
                </div>
            </div> <!-- card end// -->
            
        </section> <!-- content-main end// -->
{% endblock %}

templates/myadmin/edit_orderlist.html
{% extends 'myadmin/base.html' %}
{% block content %}
{% load static %}
        <section class="content-main">
            <div class="content-header">
                <div>
                    <h2 class="content-title card-title">Edit order</h2>
                    <p>Edit your order here</p>
                </div>
                <div>
                    
                    <a href="{% url 'orders_list' %}" class="btn btn-primary btn-sm rounded">back</a>
                </div>
            </div>
            <div class="card mb-4">
                <div class="card-body">
                    <form method="POST">
                        {% csrf_token %}
                        <label>Select user</label><br>
                        <select name="user" class="form-control" style="width:200px;"><br>
                            {% for i in all_users %}
                                <option value="{{i.id}}" {% if i.id == my_order.user.id %}selected{% endif %}>{{i.username}}</option>
                            {% endfor %}
                        </select><br><br>
                        <label>Change product</label><br>
                        <select name="product" class="form-control" style="width:200px;">
                            {% for i in all_products %}
                                <option value="{{i.id}}" {% if i.id == my_order.Product.id %}selected{% endif %}>{{i.title}}</option>
                            {% endfor %}
                        </select><br><br>
                        <label>My address</label><br>
                        <select name="address" class="form-control" style="width:200px;">
                            {% for i in all_address %}
                                <option value="{{i.id}}" {% if i.id == my_order.address.id %}selected{% endif %}>{{i.name}}-{{i.locality}}-{{i.city}}</option>
                            {% endfor %}
                        </select><br><br>
                        <label>Quantity</label><br>
                        <input type="number" name="quantity" class="form-control" style="width:200px;" value="{{my_order.quantity}}"><br><br>
                        <label>Order Status</label><br>
                        <select name="status" class="form-control" style="width:200px;">
                            {% for i in status_choices %}
                                <option value="{{i.0}}" {% if i.0 == my_order.status %}selected{% endif %}>{{i.1}}</option>
                            {% endfor %}
                        </select><br><br>
                        <label>Delivery_date</label><br>
                        <input type="datetime-local" id="id_delivery_date" name="delivery_date" class="form-control" style="width:200px;" value="{{ my_order.delivery_date|date:'Y-m-d\TH:i' }}"><br><br>
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </form>
                </div> <!-- card-body end// -->
            </div> <!-- card end// -->
            
        </section> <!-- content-main end// -->
{% endblock %}

templates/myadmin/edit_subcat_list.html
{% extends 'myadmin/base.html' %}
{% block content %}
{% load static %}
        <section class="content-main">
            <div class="content-header">
                <div>
                    <h2 class="content-title card-title">Edit Brand</h2>
                    
                </div>
                <div>
                    <a href="#" class="btn btn-light rounded font-md">Export</a>
                    <a href="#" class="btn btn-light rounded  font-md">Import</a>
                    <a href="{% url 'maincat_list' %}" class="btn btn-primary btn-sm rounded">back</a>
                </div>
            </div>
            <div class="card mb-4">
                 <!-- card-header end// -->
                <div class="card-body">
                    <form method="POST">
                        {% csrf_token %}
                                    
                            {% if messages %}
                                {% for msg in messages %}
                                    <p class="message {% if message.tags %}{{ message.tags }}{% endif %}">{{msg}}</p>
                                {% endfor %}
                            {% endif %}
                        <div>
                            <label for="username">Category name:</label>
                                <input type="text" id="brandname" name="brandname" value="{{ sub_category.name }}" required><br><br>
                                        
                                <button type="submit">Edit</button><br><br>
                        </div>
                    </form>
                </div> <!-- card-body end// -->
            </div> <!-- card end// -->
            
        </section> <!-- content-main end// -->
{% endblock %}
                

templates/myadmin/my_couponlist.html
{% extends 'myadmin/base.html' %}
{% block content %}
{% load static %}
<section class="content-main">
    <div class="content-header">
        <div>
            <h2 class="content-title card-title">{{user.username}} 's  used coupons</h2>
            <p>Delete to make user reuse the coupon</p>
        </div>
        <div>
            <a href="{% url 'userslist_coupon' %}" class="btn btn-primary btn-sm rounded">back</a>
            
        </div>
    </div>
    <div class="card mb-4">
        
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-hover">
                    <thead>
                        <tr>
                            <th>#ID</th>
                            <th scope="col">Coupon Code</th>
                            <th scope="col" class="text-end"> Actions </th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for i in my_coupons %}
                        <tr>
                            <td>{{forloop.counter}}</td>
                            <td><b>{{ i.coupon.code }}</b></td>
                            
                            
                            <td class="text-end">
                                <a href="{% url 'delete_mycoupon' i.id %}" class="btn btn-md rounded font-sm">Delete</a>
                            </td>
                        </tr>
                        {% endfor %}
                        
                    </tbody>
                </table>
            </div> <!-- table-responsive //end -->
        </div>
    </div> <!-- card end// -->
    
</section>
{% endblock %}